Update rbenv-plugin

diff --git a/bin/rbenv-plugin b/bin/rbenv-plugin
--- a/bin/rbenv-plugin
+++ b/bin/rbenv-plugin
@@ -27,7 +27,10 @@ rm() {
     echo "Cannot delete update plugin" >&2
     exit 1
   fi
-  rm -rf "$RBENV_PLUGINS_ROOT/$NAME" || { echo "Cannot delete rbenv plugin $1" >&2 ; exit 1 }
+  if ! rm -rf "$RBENV_PLUGINS_ROOT/$NAME"; then
+    echo "Cannot delete rbenv plugin $1" >&2
+    exit 1
+  fi
   echo "Deleted rbenv plugin $1"
 }
 
